parameters:
    youshido.uploadable.namer: Youshido\UploadableBundle\Tools\Namer\Md5HashNamer
    youshido.uploadable.base_upload_dir: %kernel.root_dir%/../web/uploads

services:
    uploadable.reader:
        class: Youshido\UploadableBundle\Annotations\Reader\UploadableReader

    uploadable.namer:
        class: %youshido.uploadable.namer%

    uploadable.file_manager:
        class: Youshido\UploadableBundle\Manager\FileManager
        arguments: [ @uploadable.namer ]
        calls:
            - [ setBaseUploadDir, [%youshido.uploadable.base_upload_dir%] ]
            - [ setContainer, [@service_container]]

    uploadable.listener:
        class: Youshido\UploadableBundle\Listener\UploadableListener
        arguments: [ @uploadable.reader, @uploadable.file_manager ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    uploadable.form.type.youshido_file:
        class: Youshido\UploadableBundle\Type\FileType
        arguments: [ @uploadable.reader, @validator ]
        tags:
          - { name: form.type, alias: youshido_file }